# Generated by Django 6.0 on 2026-02-10 22:15

import medicine_identifier.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_identifier', '0002_alter_medicineidentification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineidentification',
            name='supabase_image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='medicineidentification',
            name='image',
            field=models.ImageField(storage=medicine_identifier.models.get_medicine_storage, upload_to='medicine_images/'),
        ),
    ]
